
import React, { createContext, useContext, useState, ReactNode } from 'react';

type Language = 'IT' | 'EN' | 'FR' | 'DE' | 'ES' | 'PT' | 'RU' | 'ZH' | 'JA' | 'KO';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations = {
  IT: {
    'site.title': 'Direct Democracy Project',
    'nav.home': 'Home',
    'nav.polls': 'Sondaggi',
    'nav.dashboard': 'Dashboard',
    'nav.news': 'News & Trasparenza',
    'nav.login': 'Accedi',
    'nav.guest': 'Ospite',
    'polls.title': 'Sondaggi Attivi',
    'polls.subtitle': 'Partecipa alle decisioni che influenzano il futuro del paese',
    'polls.search': 'Cerca sondaggi...',
    'polls.participate': 'Partecipa',
    'polls.details': 'Dettagli',
    'polls.active': 'ATTIVO',
    'polls.urgent': 'URGENTE',
    'polls.expired': 'SCADUTO',
    'poll.participants': 'Partecipanti',
    'poll.deadline': 'Scadenza',
    'poll.scope': 'Ambito',
    'poll.vote': 'Esprimi il tuo voto',
    'poll.submit': 'Invia Voto',
    'poll.voted': 'Voto Registrato',
    'poll.thanks': 'Grazie per aver partecipato!',
    'footer.description': 'Piattaforma digitale per la partecipazione democratica diretta. Costruiamo insieme il futuro della democrazia italiana.',
    'footer.legal': 'Informazioni Legali',
    'footer.community': 'Comunità',
    'footer.copyright': '© 2025 Direct Democracy Project. Tutti i diritti riservati.',
    'footer.certification': 'Piattaforma certificata conforme alle normative europee sulla sicurezza digitale (eIDAS)'
  },
  EN: {
    'site.title': 'Direct Democracy Project',
    'nav.home': 'Home',
    'nav.polls': 'Polls',
    'nav.dashboard': 'Dashboard',
    'nav.news': 'News & Transparency',
    'nav.login': 'Login',
    'nav.guest': 'Guest',
    'polls.title': 'Active Polls',
    'polls.subtitle': 'Participate in decisions that shape the country\'s future',
    'polls.search': 'Search polls...',
    'polls.participate': 'Participate',
    'polls.details': 'Details',
    'polls.active': 'ACTIVE',
    'polls.urgent': 'URGENT',
    'polls.expired': 'EXPIRED',
    'poll.participants': 'Participants',
    'poll.deadline': 'Deadline',
    'poll.scope': 'Scope',
    'poll.vote': 'Cast your vote',
    'poll.submit': 'Submit Vote',
    'poll.voted': 'Vote Recorded',
    'poll.thanks': 'Thank you for participating!',
    'footer.description': 'Digital platform for direct democratic participation. Building the future of Italian democracy together.',
    'footer.legal': 'Legal Information',
    'footer.community': 'Community',
    'footer.copyright': '© 2025 Direct Democracy Project. All rights reserved.',
    'footer.certification': 'Platform certified compliant with European digital security regulations (eIDAS)'
  },
  FR: {
    'site.title': 'Projet de Démocratie Directe',
    'nav.home': 'Accueil',
    'nav.polls': 'Sondages',
    'nav.dashboard': 'Tableau de bord',
    'nav.news': 'Actualités & Transparence',
    'nav.login': 'Connexion',
    'nav.guest': 'Invité',
    'polls.title': 'Sondages Actifs',
    'polls.subtitle': 'Participez aux décisions qui façonnent l\'avenir du pays',
    'polls.search': 'Rechercher des sondages...',
    'polls.participate': 'Participer',
    'polls.details': 'Détails',
    'polls.active': 'ACTIF',
    'polls.urgent': 'URGENT',
    'polls.expired': 'EXPIRÉ',
    'poll.participants': 'Participants',
    'poll.deadline': 'Date limite',
    'poll.scope': 'Portée',
    'poll.vote': 'Exprimez votre vote',
    'poll.submit': 'Soumettre le vote',
    'poll.voted': 'Vote enregistré',
    'poll.thanks': 'Merci de votre participation !',
    'footer.description': 'Plateforme numérique pour la participation démocratique directe. Construisons ensemble l\'avenir de la démocratie italienne.',
    'footer.legal': 'Informations légales',
    'footer.community': 'Communauté',
    'footer.copyright': '© 2025 Projet de Démocratie Directe. Tous droits réservés.',
    'footer.certification': 'Plateforme certifiée conforme aux réglementations européennes de sécurité numérique (eIDAS)'
  },
  // Add more languages...
  DE: {
    'site.title': 'Direkte Demokratie Projekt',
    'nav.home': 'Startseite',
    'nav.polls': 'Umfragen',
    'nav.dashboard': 'Dashboard',
    'nav.news': 'Nachrichten & Transparenz',
    'nav.login': 'Anmelden',
    'nav.guest': 'Gast',
    'polls.title': 'Aktive Umfragen',
    'polls.subtitle': 'Beteiligen Sie sich an Entscheidungen, die die Zukunft des Landes prägen',
    'polls.search': 'Umfragen suchen...',
    'polls.participate': 'Teilnehmen',
    'polls.details': 'Details',
    'polls.active': 'AKTIV',
    'polls.urgent': 'DRINGEND',
    'polls.expired': 'ABGELAUFEN',
    'poll.participants': 'Teilnehmer',
    'poll.deadline': 'Frist',
    'poll.scope': 'Umfang',
    'poll.vote': 'Ihre Stimme abgeben',
    'poll.submit': 'Stimme abgeben',
    'poll.voted': 'Stimme aufgezeichnet',
    'poll.thanks': 'Vielen Dank für Ihre Teilnahme!',
    'footer.description': 'Digitale Plattform für direkte demokratische Teilnahme. Gemeinsam die Zukunft der italienischen Demokratie gestalten.',
    'footer.legal': 'Rechtliche Informationen',
    'footer.community': 'Gemeinschaft',
    'footer.copyright': '© 2025 Direkte Demokratie Projekt. Alle Rechte vorbehalten.',
    'footer.certification': 'Plattform zertifiziert konform mit europäischen digitalen Sicherheitsvorschriften (eIDAS)'
  },
  ES: {
    'site.title': 'Proyecto de Democracia Directa',
    'nav.home': 'Inicio',
    'nav.polls': 'Encuestas',
    'nav.dashboard': 'Panel',
    'nav.news': 'Noticias & Transparencia',
    'nav.login': 'Iniciar sesión',
    'nav.guest': 'Invitado',
    'polls.title': 'Encuestas Activas',
    'polls.subtitle': 'Participa en las decisiones que dan forma al futuro del país',
    'polls.search': 'Buscar encuestas...',
    'polls.participate': 'Participar',
    'polls.details': 'Detalles',
    'polls.active': 'ACTIVO',
    'polls.urgent': 'URGENTE',
    'polls.expired': 'EXPIRADO',
    'poll.participants': 'Participantes',
    'poll.deadline': 'Fecha límite',
    'poll.scope': 'Alcance',
    'poll.vote': 'Emite tu voto',
    'poll.submit': 'Enviar voto',
    'poll.voted': 'Voto registrado',
    'poll.thanks': '¡Gracias por participar!',
    'footer.description': 'Plataforma digital para la participación democrática directa. Construyendo juntos el futuro de la democracia italiana.',
    'footer.legal': 'Información legal',
    'footer.community': 'Comunidad',
    'footer.copyright': '© 2025 Proyecto de Democracia Directa. Todos los derechos reservados.',
    'footer.certification': 'Plataforma certificada conforme a las regulaciones europeas de seguridad digital (eIDAS)'
  },
  PT: {
    'site.title': 'Projeto de Democracia Direta',
    'nav.home': 'Início',
    'nav.polls': 'Pesquisas',
    'nav.dashboard': 'Painel',
    'nav.news': 'Notícias & Transparência',
    'nav.login': 'Entrar',
    'nav.guest': 'Convidado',
    'polls.title': 'Pesquisas Ativas',
    'polls.subtitle': 'Participe nas decisões que moldam o futuro do país',
    'polls.search': 'Pesquisar enquetes...',
    'polls.participate': 'Participar',
    'polls.details': 'Detalhes',
    'polls.active': 'ATIVO',
    'polls.urgent': 'URGENTE',
    'polls.expired': 'EXPIRADO',
    'poll.participants': 'Participantes',
    'poll.deadline': 'Prazo',
    'poll.scope': 'Escopo',
    'poll.vote': 'Emita seu voto',
    'poll.submit': 'Enviar voto',
    'poll.voted': 'Voto registrado',
    'poll.thanks': 'Obrigado por participar!',
    'footer.description': 'Plataforma digital para participação democrática direta. Construindo juntos o futuro da democracia italiana.',
    'footer.legal': 'Informações legais',
    'footer.community': 'Comunidade',
    'footer.copyright': '© 2025 Projeto de Democracia Direta. Todos os direitos reservados.',
    'footer.certification': 'Plataforma certificada em conformidade com os regulamentos europeus de segurança digital (eIDAS)'
  },
  RU: {
    'site.title': 'Проект Прямой Демократии',
    'nav.home': 'Главная',
    'nav.polls': 'Опросы',
    'nav.dashboard': 'Панель',
    'nav.news': 'Новости & Прозрачность',
    'nav.login': 'Войти',
    'nav.guest': 'Гость',
    'polls.title': 'Активные опросы',
    'polls.subtitle': 'Участвуйте в решениях, формирующих будущее страны',
    'polls.search': 'Поиск опросов...',
    'polls.participate': 'Участвовать',
    'polls.details': 'Детали',
    'polls.active': 'АКТИВНЫЙ',
    'polls.urgent': 'СРОЧНЫЙ',
    'polls.expired': 'ИСТЁК',
    'poll.participants': 'Участники',
    'poll.deadline': 'Срок',
    'poll.scope': 'Область',
    'poll.vote': 'Отдайте свой голос',
    'poll.submit': 'Отправить голос',
    'poll.voted': 'Голос записан',
    'poll.thanks': 'Спасибо за участие!',
    'footer.description': 'Цифровая платформа для прямого демократического участия. Строим будущее итальянской демократии вместе.',
    'footer.legal': 'Правовая информация',
    'footer.community': 'Сообщество',
    'footer.copyright': '© 2025 Проект Прямой Демократии. Все права защищены.',
    'footer.certification': 'Платформа сертифицирована в соответствии с европейскими правилами цифровой безопасности (eIDAS)'
  },
  ZH: {
    'site.title': '直接民主项目',
    'nav.home': '首页',
    'nav.polls': '投票',
    'nav.dashboard': '仪表板',
    'nav.news': '新闻与透明度',
    'nav.login': '登录',
    'nav.guest': '访客',
    'polls.title': '活跃投票',
    'polls.subtitle': '参与塑造国家未来的决策',
    'polls.search': '搜索投票...',
    'polls.participate': '参与',
    'polls.details': '详情',
    'polls.active': '活跃',
    'polls.urgent': '紧急',
    'polls.expired': '已过期',
    'poll.participants': '参与者',
    'poll.deadline': '截止日期',
    'poll.scope': '范围',
    'poll.vote': '投出您的一票',
    'poll.submit': '提交投票',
    'poll.voted': '投票已记录',
    'poll.thanks': '感谢您的参与！',
    'footer.description': '直接民主参与的数字平台。共同建设意大利民主的未来。',
    'footer.legal': '法律信息',
    'footer.community': '社区',
    'footer.copyright': '© 2025 直接民主项目。保留所有权利。',
    'footer.certification': '平台已通过欧洲数字安全法规(eIDAS)认证'
  },
  JA: {
    'site.title': '直接民主プロジェクト',
    'nav.home': 'ホーム',
    'nav.polls': '投票',
    'nav.dashboard': 'ダッシュボード',
    'nav.news': 'ニュース＆透明性',
    'nav.login': 'ログイン',
    'nav.guest': 'ゲスト',
    'polls.title': 'アクティブな投票',
    'polls.subtitle': '国の未来を形作る決定に参加しましょう',
    'polls.search': '投票を検索...',
    'polls.participate': '参加',
    'polls.details': '詳細',
    'polls.active': 'アクティブ',
    'polls.urgent': '緊急',
    'polls.expired': '期限切れ',
    'poll.participants': '参加者',
    'poll.deadline': '締切',
    'poll.scope': '範囲',
    'poll.vote': '投票する',
    'poll.submit': '投票を送信',
    'poll.voted': '投票が記録されました',
    'poll.thanks': 'ご参加ありがとうございます！',
    'footer.description': '直接民主的参加のためのデジタルプラットフォーム。イタリア民主主義の未来を一緒に築きます。',
    'footer.legal': '法的情報',
    'footer.community': 'コミュニティ',
    'footer.copyright': '© 2025 直接民主プロジェクト。全著作権所有。',
    'footer.certification': 'プラットフォームは欧州デジタルセキュリティ規則(eIDAS)に準拠し認証されています'
  },
  KO: {
    'site.title': '직접민주주의 프로젝트',
    'nav.home': '홈',
    'nav.polls': '투표',
    'nav.dashboard': '대시보드',
    'nav.news': '뉴스 & 투명성',
    'nav.login': '로그인',
    'nav.guest': '게스트',
    'polls.title': '활성 투표',
    'polls.subtitle': '국가의 미래를 형성하는 결정에 참여하세요',
    'polls.search': '투표 검색...',
    'polls.participate': '참여',
    'polls.details': '세부사항',
    'polls.active': '활성',
    'polls.urgent': '긴급',
    'polls.expired': '만료됨',
    'poll.participants': '참가자',
    'poll.deadline': '마감일',
    'poll.scope': '범위',
    'poll.vote': '투표하기',
    'poll.submit': '투표 제출',
    'poll.voted': '투표 기록됨',
    'poll.thanks': '참여해 주셔서 감사합니다!',
    'footer.description': '직접 민주적 참여를 위한 디지털 플랫폼. 이탈리아 민주주의의 미래를 함께 건설합니다.',
    'footer.legal': '법적 정보',
    'footer.community': '커뮤니티',
    'footer.copyright': '© 2025 직접민주주의 프로젝트. 모든 권리 보유.',
    'footer.certification': '플랫폼은 유럽 디지털 보안 규정(eIDAS)을 준수하여 인증되었습니다'
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>('IT');

  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations[Language]] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
